services:
  mongo-branch:
    image: mongo
    container_name: mongo-branch
    ports:
      - "27091:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  mongo-exp-branch:
    image: mongo-express
    container_name: mongo-exp-branch
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongo-branch
volumes:
  data: {}
#networks:
#  default:
#    name: mongo-net-branch