
services:
  file-manager-db:
    image: mysql
    networks:
      - write-2-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=file-manager
    container_name: file-manager-db

  file-manager-app:
#    build:
#      dockerfile: Dockerfile
    image: file-management-write:latest
    restart: on-failure
    ports:
      - "8094:8094"
    networks:
      - write-2-db
    depends_on:
      - file-manager-db
    container_name: file-manager-app

networks:
  write-2-db: {}